{"timestamp": "2025-10-13T00:34:09.001220", "level": "INFO", "logger": "opinion_market", "message": "{\"level\": \"info\", \"format\": \"json\", \"event\": \"Logging system initialized\", \"logger\": \"opinion_market\", \"timestamp\": \"2025-10-13T00:34:09.001136Z\"}", "module": "logging", "function": "setup_logging", "line": 201, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.155327", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.155734", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.155998", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.163286", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.163969", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.182510", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.185102", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
{"timestamp": "2025-10-13T00:34:09.193597", "level": "WARNING", "logger": "app.core.database", "message": "Redis connection failed: Error 61 connecting to localhost:6379. Connection refused.", "module": "database", "function": "get_redis_client", "line": 99, "taskName": null}
